name: Notify

on:
  push:
    branches-ignore:
      - latest


jobs:
     Notify:
      runs-on: ubuntu-latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - name: Check for Issues
          run: |
            gh issue list --repo Grants52/hello-world-appgs -l '⏱ Awaiting triage'
            result="$(gh issue list --repo Grants52/hello-world-appgs -l '⏱ Awaiting triage' 2>&1)"
            
        - name: send slack message
          env:
             ISSUES_URL: https://github.com/Grants52/hello-world-appgs/issues?q=is%3Aissue+is%3Aopen+label%3A%22%E2%8F%B1+Awaiting+triage%22
          run: |
            slack_triage () {
            curl -X POST -H 'Content-type: application/json' --data '{"text":"There are <'$ISSUES_URL'|Triage issues> to review this morning"}'  
            ${{ secrets.SLACK_TOKEN }}
            }
            if [[  `echo $result` == Showing* ]]; then slack_triage ; else slack_notriage; fi
            
            
            #curl -X POST -H 'Content-type: application/json' --data '{"text":"testing"}' ${{ secrets.SLACK_TOKEN }}
        
