name: Notify

on:
  push:
    branches-ignore:
      - latest


jobs:
     Notify:
      runs-on: ubuntu-latest
      steps:
        - name: Check for Issues
          run: |
            gh issue list --repo Grants52/hello-world-appgs -l '⏱ Awaiting triage'

        
