name: Notify

on:
  push:
    branches-ignore:
      - latest


jobs:
     Notify:
      runs-on: ubuntu-latest
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - name: Check for Issues
          run: |
            gh issue list --repo Grants52/hello-world-appgs -l '⏱ Awaiting triage'
            
        - name: send slack message
          run: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' ${{ secrets.GITHUB_TOKEN }}
        
